[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "lfm"
version = "0.0.1"
description = "Movie Recommendation System based on Latent Factor Model (LFM) Algorithm"
authors = [
  { name = "Sitong Chen", email = "your@email.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9.11"
dynamic = ["dependencies", "optional-dependencies"]

[tool.setuptools]
packages = ["lfm"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = ['requirements_dev.txt']}

[tool.ruff]
line-length = 120
